### ISSUE TITLE
Reformat help message

### ISSUE THREAD

**Issue by Bluscream** [kdrag0n/pyrobud#7]
It would be helpful if the help message had a slightly different format:

```
**Module**:
    • `<prefix>command`: Description (aliases: `<prefix>alias`, `<prefix>alias2`)
```
with that it would be easier to just click/tap on the command to copy it for usage ^^

Another nice addition would be the ability to only show help for a specific module by providing it's name as argument

**Comment by kdrag0n** [comment]
Unfortunately that help format isn't viable since the maximum number of text entities per message is limited. With the current set of commands, it cuts off while listing commands in the Stickers module:
![image](https://user-images.githubusercontent.com/7930239/68988423-0d989080-07ec-11ea-982b-d64732cc295f.png)

The second point has been addressed with commit 2f603b0.

**Comment by Bluscream** [comment]
That's too bad bad. I'm sure help will get too big for a single message soon anyway :o

**Comment by Bluscream** [comment]
@Bluscream

**Comment by Bluscream** [comment]
Truncation is not a viable solution for a more or less dynamic help message.

We need to either use chunks or pagination here.
